version: 0.2
phases:
    install:
        runtime-versions:
            java: correctto17
    build:
        commands:
            - echo BUild started on `date`
            - mvn package -Dmaven.test.skip=true
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - scripts/**
        - appspec.yml
        - target/*.jar
    discard-paths: no
    
